--, IsActive                bit             -- Enable or disable a merge without deleting the record
--, SCDType                 varchar(255)    -- Slowly Changing Dimension type
--, ColumnJoin              varchar(max)    -- Columns to match on
--, ColumnValueDiff         varchar(max)    -- Columns to look for a difference in values
--, ColumnIgnore            varchar(max)    -- Columns to ignore for the update
--, DeleteIfNotMatchedBySource bit          -- Bit value to allow partial loads
